version: '3.1'

services:  
  application-link:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: application-link
    environment:
      - SERVER_PORT=$SERVER_PORT
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    restart: always
