version: '3.1'

services:
  link-db:
    image: postgres:14.3-alpine
    container_name: service-link-db
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - /shortlinks-db/service-link:/var/lib/postgresql/data
    restart: always
  
  server-link:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: service-link-server
    environment:
      - SERVER_PORT=$SERVER_PORT
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    depends_on:
      - link-db
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    restart: always
